### ISSUE TITLE
Consider using rustls vs. openssl

### ISSUE THREAD

**Issue by moderation** [liljencrantz/crush#14]
It would be good to allow the usage of `rustls` so that OpenSSL isn't required to be installed to build. Benefit is a more modern Rust based TLS implementation. Would prevent errors like:
```
error: failed to run custom build command for `openssl-sys v0.9.58`

Caused by:
  process didn't exit successfully: `~/Library/rust/crush/target/release/build/openssl-sys-b99cc26280c55ab3/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
cargo:rerun-if-env-changed=OPENSSL_DIR
OPENSSL_DIR unset
cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG
cargo:rerun-if-env-changed=OPENSSL_STATIC
cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
cargo:rerun-if-env-changed=PKG_CONFIG_PATH
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'openssl\' found\n"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

$HOST = x86_64-unknown-linux-gnu
$TARGET = x86_64-unknown-linux-gnu
openssl-sys = 0.9.58

', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.58/build/find_normal.rs:157:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by liljencrantz** [comment]
I honestly prefer to minimize *options*. Either use one or the other would be my strong preference. Is rustls ready for prime time? Who is already using it?

**Comment by moderation** [comment]
Understand wanting to minimize options. Projects like the Linkerd service mesh (https://github.com/linkerd/linkerd2-proxy) and Rusoto (https://github.com/rusoto/rusoto) use rustls. Having a native Rust implementation is likely a much better security play given OpenSSL's poor track record.

I made some progess with with `reqwest = { version = "0.10", default-features = false, features = ["blocking", "rustls-tls"] }` which leaves ssh2 pulling in `openssl-sys`. I was able to build using just `openssl-sys` with the following `Cargo.toml`:

```toml
[package]
name = "crush"
version = "0.1.0"
authors = ["Axel Liljencrantz <liljencrantz@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
description = "A command line shell that is also a powerful and modern programming language"
readme = "README.md"
repository = "https://github.com/liljencrantz/crush"

[build-dependencies.prost-build]
version = "0.6"

[build-dependencies.lalrpop]
version = "0.19"
features = ["lexer"]

[workspace]
members = [
    "signature",
    "ordered_map",
]

[dependencies.signature]
path = "signature"

[dependencies.ordered_map]
path = "ordered_map"

[dependencies]
bytes = "0.5"
chrono = "0.4"
crossbeam = "0.7"
dirs = "3"
float-ord = "0.2"
lalrpop-util = "0.19"
lazy_static = "1"
maplit = "1"
nix = "0.18"
openssl-sys = { version = "0.9", features = ["vendored"] }
prost = "0.6"
psutil = "1" # psutil 2 and 3 break
rand = "0.7"
regex = "1"
reqwest = { version = "0.10", default-features = false, features = ["blocking", "rustls-tls"] }
rustyline = "6"
serde_json = "1"
ssh2 = "0.8"
sys-info = "0.7"
termion = "1"
time = "0.1" # time 2 breaks
toml = "0.5"
users = "0.10"
```
Closing as I think it would be difficult to remove the downstream dependency. The above `Cargo.toml` should allow people to buld `crush` without installing `openssl` first.
